[tool.poetry]
name = "customer-data-analysis"
version = "0.1.0"
description = ""
authors = ["Daffa Ilhami <mdaffailhami@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
